# Generated by Django 2.2.1 on 2019-07-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=20, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('stu_class', models.CharField(max_length=50, verbose_name='班级')),
                ('stu_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('stu_phone', models.CharField(max_length=20, verbose_name='电话')),
                ('stu_addr', models.CharField(max_length=50, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, verbose_name='工号')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('teacher_office', models.CharField(max_length=20, verbose_name='办公室')),
                ('teacher_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('teacher_phone', models.CharField(max_length=20, verbose_name='电话')),
                ('teacher_addr', models.CharField(max_length=50, verbose_name='地址')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_sign_time', models.DateTimeField(verbose_name='签到时间')),
                ('stu_sign_status', models.CharField(max_length=10, verbose_name='签到状态')),
                ('course', models.CharField(max_length=50, verbose_name='课程名称')),
                ('classroom', models.CharField(max_length=50, verbose_name='教室')),
                ('stu_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Student')),
                ('teacher_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Teacher')),
            ],
        ),
    ]
