# Generated by Django 2.2.3 on 2019-07-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherFaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trained', models.BooleanField(verbose_name='是否训练')),
                ('teacher_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Teacher')),
            ],
            options={
                'verbose_name': '教师人脸数据',
                'verbose_name_plural': '教师人脸数据',
            },
        ),
        migrations.CreateModel(
            name='StudentFaceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trained', models.BooleanField(verbose_name='是否训练')),
                ('stu_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Student')),
            ],
            options={
                'verbose_name': '学生人脸数据',
                'verbose_name_plural': '学生人脸数据',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_sign_time', models.DateTimeField(auto_now=True, verbose_name='签到时间')),
                ('stu_sign_status', models.CharField(max_length=10, verbose_name='签到状态')),
                ('course', models.CharField(max_length=50, verbose_name='课程名称')),
                ('classroom', models.CharField(max_length=50, verbose_name='教室')),
                ('stu_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Student')),
                ('teacher_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Teacher')),
            ],
            options={
                'verbose_name': '课程签到情况',
                'verbose_name_plural': '课程签到情况',
            },
        ),
    ]
