# Generated by Django 2.2.3 on 2019-07-25 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherfacedata',
            name='teacher_info',
        ),
        migrations.AlterField(
            model_name='course',
            name='stu_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teacher_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.Teacher', verbose_name='教师'),
        ),
        migrations.DeleteModel(
            name='StudentFaceData',
        ),
        migrations.DeleteModel(
            name='TeacherFaceData',
        ),
    ]
