# Generated by Django 2.2.1 on 2019-07-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20190714_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教师', 'verbose_name_plural': '教师'},
        ),
    ]
