# Generated by Django 2.2.3 on 2019-07-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=20, verbose_name='学号')),
                ('stu_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('stu_class', models.CharField(max_length=50, verbose_name='班级')),
                ('stu_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('stu_phone', models.CharField(max_length=20, verbose_name='电话')),
                ('stu_addr', models.CharField(max_length=50, verbose_name='地址')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, verbose_name='工号')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='姓名')),
                ('teacher_office', models.CharField(max_length=20, verbose_name='办公室')),
                ('teacher_email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('teacher_phone', models.CharField(max_length=20, verbose_name='电话')),
                ('teacher_addr', models.CharField(max_length=50, verbose_name='地址')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
    ]
